/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menuxdd;
import clases.animacion_up;
import clases.animacion_down;

import AppPackage.AnimationClass;
/**
 *
 * @author Angel
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu1 = new javax.swing.JLabel();
        Menu2 = new javax.swing.JLabel();
        Menu3 = new javax.swing.JLabel();
        Menu5 = new javax.swing.JLabel();
        Menu6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Menu4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Iogo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Music = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Today_96px.png"))); // NOI18N
        Menu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu1MouseMoved(evt);
            }
        });
        Menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu1MouseExited(evt);
            }
        });
        jPanel1.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 183, 153));

        Menu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-papelera2-x96.png"))); // NOI18N
        Menu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu2MouseMoved(evt);
            }
        });
        Menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu2MouseExited(evt);
            }
        });
        jPanel1.add(Menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 183, 153));

        Menu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Maintenance_96px.png"))); // NOI18N
        Menu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu3MouseMoved(evt);
            }
        });
        Menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu3MouseExited(evt);
            }
        });
        jPanel1.add(Menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 183, 153));

        Menu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icone-carpeta-x96.png"))); // NOI18N
        Menu5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu5MouseMoved(evt);
            }
        });
        Menu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu5MouseExited(evt);
            }
        });
        jPanel1.add(Menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 183, 153));

        Menu6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-calculadora-x96.png"))); // NOI18N
        Menu6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Menu6MouseMoved(evt);
            }
        });
        Menu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu6MouseExited(evt);
            }
        });
        jPanel1.add(Menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 183, 153));

        jLabel8.setBackground(new java.awt.Color(255, 99, 71));
        jLabel8.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 99, 71));
        jLabel8.setText("Agregar Producto");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 99, 71));
        jLabel9.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 99, 71));
        jLabel9.setText("Eliminar Producto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("Modificar Producto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Mostrar Todo");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("Mostrar Producto");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel15.setBackground(new java.awt.Color(255, 99, 71));
        jLabel15.setFont(new java.awt.Font("Poppins Medium", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 99, 71));
        jLabel15.setText("Calcular Ventas");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        Menu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Menu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icone-ojo-x96.png"))); // NOI18N
        Menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Menu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Menu4MouseExited(evt);
            }
        });
        jPanel1.add(Menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 183, 153));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 760, 530));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 99, 71));
        jLabel13.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 99, 71));
        jLabel13.setText("Gestor De Inventario");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 260, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Search_32px_2.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 760, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Iogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Globe_32px.png"))); // NOI18N
        jPanel3.add(Iogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 230, 40, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Menu_32px.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Musical_Notes_32px.png"))); // NOI18N
        jPanel3.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 270, 40, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseMoved
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu1; 
        anim1.anim_up_up();
        AnimationClass grande = new AnimationClass();
    }//GEN-LAST:event_Menu1MouseMoved

    private void Menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu1MouseExited
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu1; 
        anim1.anim_down_up();
    }//GEN-LAST:event_Menu1MouseExited

    private void Menu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseMoved
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu2; 
        anim1.anim_up_up();
    }//GEN-LAST:event_Menu2MouseMoved

    private void Menu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu2MouseExited
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu2; 
        anim1.anim_down_up();
    }//GEN-LAST:event_Menu2MouseExited

    private void Menu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseMoved
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu3; 
        anim1.anim_up_up();
    }//GEN-LAST:event_Menu3MouseMoved

    private void Menu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu3MouseExited
        animacion_up anim1 = new animacion_up();
        anim1.lable = Menu3; 
        anim1.anim_down_up();
    }//GEN-LAST:event_Menu3MouseExited

    private void Menu5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseMoved
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu5; 
        anim1.anim_up_down();
    }//GEN-LAST:event_Menu5MouseMoved

    private void Menu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu5MouseExited
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu5; 
        anim1.anim_down_down();
    }//GEN-LAST:event_Menu5MouseExited

    private void Menu6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseMoved
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu6; 
        anim1.anim_up_down();
    }//GEN-LAST:event_Menu6MouseMoved

    private void Menu6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu6MouseExited
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu6; 
        anim1.anim_down_down();
    }//GEN-LAST:event_Menu6MouseExited

    private void Menu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseEntered
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu4; 
        anim1.anim_up_down();
    }//GEN-LAST:event_Menu4MouseEntered

    private void Menu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu4MouseExited
        animacion_down anim1 = new animacion_down();
        anim1.label_down = Menu4; 
        anim1.anim_down_down();
    }//GEN-LAST:event_Menu4MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        AnimationClass logo_r = new AnimationClass();
        logo_r.jLabelXRight(-30, 5, 10, 10, Iogo);
        
        AnimationClass music_r = new AnimationClass();
        music_r.jLabelXRight(-30, 5, 10, 10, Music);
        
        
        
        //<--------
        
        AnimationClass logo_l = new AnimationClass();
        logo_l.jLabelXLeft(5, -30, 10, 5, Iogo);
        
        AnimationClass music_l = new AnimationClass();
        music_l.jLabelXLeft(5, -30, 10, 5, Music);     
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Iogo;
    private javax.swing.JLabel Menu1;
    private javax.swing.JLabel Menu2;
    private javax.swing.JLabel Menu3;
    private javax.swing.JLabel Menu4;
    private javax.swing.JLabel Menu5;
    private javax.swing.JLabel Menu6;
    private javax.swing.JLabel Music;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
